package com.mycompany.sqlconnection;

import java.sql.Connection;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shera
 */
public class Borrower extends javax.swing.JFrame {
    public String url = "jdbc:mysql://localhost:3306/test";
    public String user = "root";
    public String passowrd = "123456789";
   
    public Borrower() {
        initComponents();
    }
    public void Borrowerpage()throws Exception{
        
        
           Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection(url, user, passowrd);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Button_overdue = new javax.swing.JButton();
        Button_Borrowed = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label_Borrower = new javax.swing.JLabel();
        Button_EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_overdue.setBackground(new java.awt.Color(204, 0, 0));
        Button_overdue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_overdue.setForeground(new java.awt.Color(255, 255, 255));
        Button_overdue.setText("Overdue");
        Button_overdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_overdueActionPerformed(evt);
            }
        });
        jPanel2.add(Button_overdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, 50));

        Button_Borrowed.setBackground(new java.awt.Color(204, 0, 0));
        Button_Borrowed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_Borrowed.setForeground(new java.awt.Color(255, 255, 255));
        Button_Borrowed.setText("Borrowed Books");
        Button_Borrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BorrowedActionPerformed(evt);
            }
        });
        jPanel2.add(Button_Borrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        label_Borrower.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_Borrower.setText("Borrower");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(label_Borrower, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_Borrower, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, 50));

        Button_EXIT.setBackground(new java.awt.Color(204, 0, 0));
        Button_EXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_EXIT.setForeground(new java.awt.Color(255, 255, 255));
        Button_EXIT.setText("EXIT");
        Button_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EXITActionPerformed(evt);
            }
        });
        jPanel2.add(Button_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_overdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_overdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_overdueActionPerformed

    private void Button_BorrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BorrowedActionPerformed
        new Borrower().setVisible(true);
        Borrowed_Books bb = new Borrowed_Books();
        bb.setVisible(true);
    }//GEN-LAST:event_Button_BorrowedActionPerformed

    private void Button_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EXITActionPerformed

        setVisible(false);
        new LogIn().setVisible(true);
    }//GEN-LAST:event_Button_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void borrow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Borrowed;
    private javax.swing.JButton Button_EXIT;
    private javax.swing.JButton Button_overdue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Borrower;
    // End of variables declaration//GEN-END:variables
}
