/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sqlconnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author shera
 */
public class Borrower_Details extends javax.swing.JFrame {
      

    /**
     * Creates new form Borrower_Details
     */
    public Borrower_Details() {
        initComponents();
    }
    public void Borrower_DetailsPage()throws Exception{
        
        
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_borrowerName = new javax.swing.JTextField();
        txt_bookName = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Label_bookID = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Label_borrowerName = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Label_Quantity = new javax.swing.JLabel();
        Button_EXIT = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Label_bookName1 = new javax.swing.JLabel();
        txt_bookId1 = new javax.swing.JTextField();
        Button_add2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_borrowerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_borrowerNameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_borrowerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, -1));
        jPanel2.add(txt_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 230, -1));
        jPanel2.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Label_bookID.setBackground(new java.awt.Color(0, 0, 0));
        Label_bookID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_bookID.setText("Enter Book ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Label_bookID)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Label_bookID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 30));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        Label_borrowerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_borrowerName.setText("Borrower Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Label_borrowerName)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Label_borrowerName)
                .addContainerGap())
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 190, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        Label_Quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Quantity.setText("Quantity");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Label_Quantity)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 190, 30));

        Button_EXIT.setBackground(new java.awt.Color(204, 0, 0));
        Button_EXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_EXIT.setForeground(new java.awt.Color(255, 255, 255));
        Button_EXIT.setText("EXIT");
        Button_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EXITActionPerformed(evt);
            }
        });
        jPanel2.add(Button_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 110, 40));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        Label_bookName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_bookName1.setText("Enter Book Name");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Label_bookName1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(Label_bookName1)
                .addContainerGap())
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, 30));

        txt_bookId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookId1ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_bookId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 230, -1));

        Button_add2.setBackground(new java.awt.Color(204, 0, 0));
        Button_add2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_add2.setForeground(new java.awt.Color(255, 255, 255));
        Button_add2.setText("ADD");
        Button_add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_add2ActionPerformed(evt);
            }
        });
        jPanel2.add(Button_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_borrowerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_borrowerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_borrowerNameActionPerformed

    private void txt_bookId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookId1ActionPerformed

    private void Button_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EXITActionPerformed
         setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_Button_EXITActionPerformed

    private void Button_add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_add2ActionPerformed
        String BookID = txt_bookId1.getText();
        String BorrowerName = txt_borrowerName.getText();
        String BookName = txt_bookName.getText();
        String Quantity = txt_quantity.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
          
            st.executeUpdate("insert into borrower_details values('"+BookID+"','"+BorrowerName+"','"+BookName+"','"+Quantity+"')");
            JOptionPane.showMessageDialog(null, "Successfully Added");
            setVisible(false);
            new Borrower_Details().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new Borrower_Details().setVisible(true);
        }
    }//GEN-LAST:event_Button_add2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrower_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrower_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrower_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrower_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrower_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_EXIT;
    private javax.swing.JButton Button_add2;
    private javax.swing.JLabel Label_Quantity;
    private javax.swing.JLabel Label_bookID;
    private javax.swing.JLabel Label_bookName1;
    private javax.swing.JLabel Label_borrowerName;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txt_bookId1;
    private javax.swing.JTextField txt_bookName;
    private javax.swing.JTextField txt_borrowerName;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
