package com.mycompany.sqlconnection;


import java.sql.Connection;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shera
 */
public class Home extends javax.swing.JFrame {
    public String url = "jdbc:mysql://localhost:3306/test";
    public String user = "root";
    public String passowrd = "123456789";
    
    //static void home() {
     //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
   // }
       
       
    public Home() {
        initComponents();
    }
     public void Homepage()throws Exception{
        
        
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Label_LibraryRecords = new javax.swing.JLabel();
        Button_BorrowerInfo = new javax.swing.JButton();
        Button_Logout = new javax.swing.JButton();
        Button_manageBooks = new javax.swing.JButton();
        Button_LoanRecords1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Label_LibraryRecords.setBackground(new java.awt.Color(0, 0, 0));
        Label_LibraryRecords.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Label_LibraryRecords.setText("Library Records");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Label_LibraryRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_LibraryRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 270, 50));

        Button_BorrowerInfo.setBackground(new java.awt.Color(204, 0, 0));
        Button_BorrowerInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_BorrowerInfo.setForeground(new java.awt.Color(255, 255, 255));
        Button_BorrowerInfo.setText("Borrower Details");
        Button_BorrowerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BorrowerInfoActionPerformed(evt);
            }
        });
        jPanel2.add(Button_BorrowerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 200, 50));

        Button_Logout.setBackground(new java.awt.Color(255, 102, 51));
        Button_Logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_Logout.setText("Logout");
        Button_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Button_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 140, 40));

        Button_manageBooks.setBackground(new java.awt.Color(204, 0, 0));
        Button_manageBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_manageBooks.setForeground(new java.awt.Color(255, 255, 255));
        Button_manageBooks.setText("Manage Books");
        Button_manageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_manageBooksActionPerformed(evt);
            }
        });
        jPanel2.add(Button_manageBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, 50));

        Button_LoanRecords1.setBackground(new java.awt.Color(204, 0, 0));
        Button_LoanRecords1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Button_LoanRecords1.setForeground(new java.awt.Color(255, 255, 255));
        Button_LoanRecords1.setText("Loan Records");
        Button_LoanRecords1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoanRecords1ActionPerformed(evt);
            }
        });
        jPanel2.add(Button_LoanRecords1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BorrowerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BorrowerInfoActionPerformed
        new Borrower().setVisible(true);
        Borrower_Details bd = new Borrower_Details();
        bd.setVisible(true);
    }//GEN-LAST:event_Button_BorrowerInfoActionPerformed

    private void Button_manageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_manageBooksActionPerformed
        
       try{
           ManageBooks mb=new ManageBooks();
                   mb.setVisible(true);
           dispose();
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Button_manageBooksActionPerformed
 
    private void Button_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogoutActionPerformed
       
       setVisible(false);
       new LogIn().setVisible(true);
    }//GEN-LAST:event_Button_LogoutActionPerformed

    private void Button_LoanRecords1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoanRecords1ActionPerformed
        
        new LoanRecords().setVisible(true);
    }//GEN-LAST:event_Button_LoanRecords1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void home() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_BorrowerInfo;
    private javax.swing.JButton Button_LoanRecords1;
    private javax.swing.JButton Button_Logout;
    private javax.swing.JButton Button_manageBooks;
    private javax.swing.JLabel Label_LibraryRecords;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
